### ISSUE TITLE
package gor-1.3.2-1.x86_64 is intended for a different operating system

### ISSUE THREAD

**Issue by opsarno** [buger/goreplay#1004]
Linux
```bash
# cat /etc/redhat-release
CentOS Linux release 7.5.1804 (Core)

# uname -a
Linux myhost 3.10.0-862.6.3.el7.x86_64 #1 SMP Tue Jun 26 16:32:21 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

rpm errr
```bash
# rpm -ivh gor-1.3.2-1.x86_64.rpm
Preparing...                          ################################# [100%]
	package gor-1.3.2-1.x86_64 is intended for a different operating system
```

RPM package is not avaliable for centos 7.x

**Comment by cmartinez85** [comment]
It happened to me and as a workaround I modified the target in the Makefile and generated a new package with noarch instead of x64. 

`fpm --name gor --description "GoReplay is an open-source network monitoring tool which can record your live traffic, and use it for shadowing, load testing, monitoring and detailed analysis." -v DEV-1630409557 --vendor "Leonid Bugaev" -m "<support@goreplay.org>" --url "https://goreplay.org" -s dir -C /tmp/gor-build  -a all -t rpm ./=/usr/local/bin`
