### ISSUE TITLE
When --input-raw-track-response is used --http-disallow-url is ignored

### ISSUE THREAD

**Issue by MMaas3** [buger/goreplay#388]
Hi, 

I have the following gor-call:
```
./gor --input-raw :8080 --input-raw-track-response --http-disallow-url ^/static --http-disallow-url ^/$ --output-file log%Y%m%d.gz --output-file-size-limit 500m --output-file-append
```
When I request `http://localhost:8080/` gor logs the request and the response. This is not what I expect. I would have thought request would be filtered. If I remove the `--input-raw-track-response` parameter the requests are filtered like I expect.

**Comment by buger** [comment]
I think the problem is a bit deeper. I think it still filters requests, but not does not filter responses, so you see all of them. 

Problem, happens because filtering made only for request, and responses just do not touched by filter. Responses delivered to Gor separate from requests, but they still have same request id. 

To make this work, we need to add sort of dynamic map, which holds references of filtered requests, let's say for 60 seconds, and filters all responses based on that map: we check if our new map have response id as key, and if so, filter response.

Currently modifier receive only request body, without metadata [emitter.go#L67](https://github.com/buger/gor/blob/967c380dc3ca1a96c6cbabd6296b0656a6546016/emitter.go#L67)
```go
headSize := bytes.IndexByte(payload, '\n') + 1
body := payload[headSize:]
originalBodyLen := len(body)

// Instead, it should receive payload meta in addition to the body, so we can know if it is response or request.
body = modifier.Rewrite(body)
```

Request filtering itself happens here: (http_modifier.go)[https://github.com/buger/gor/blob/967c380dc3ca1a96c6cbabd6296b0656a6546016/http_modifier.go]
If you want to filter request just return empty body slice.

Alternative approach is to implement response filtering directly in emitter.go

Basic logic will look like this.

```go
var filteredRequests map[string]time.Time
....
meta := payloadMeta(payload)
requestID = string(meta[1])
body := payloadBody(payload)

if isRequestPayload(payload) {
  body = modifier.Rewrite(body)
  if len(body) == 0 {
    filteredRequests[requestID] = time.Now()
    continue
  }
} else {
  if _, ok := filteredRequests[requestID]; ok {
     delete(filteredRequests, requestID);
     continue
  }
}

... Run GC from time to time, to avoid memory leaks in cases when response not found.
now := time.Now()
for k,v := range filteredRequests {
  if now.Sub(v) > 60*time.Second {
    delete(filteredRequests, k)
  }
}
...
```

This type of long-form description is sort of experiment, and if you are looking to learn Go in details, I'm happy to provide free mentorship for all the things related to this task.

**Comment by smostovoy** [comment]
I can take this one

**Comment by MMaas3** [comment]
@smostovoy Thank you for picking up this issue. Let me know, if you have I can test.

**Comment by buger** [comment]
Fixed thanks to @smostovoy
