### ISSUE TITLE
Windows binaries missing

### ISSUE THREAD

**Issue by cerny** [buger/goreplay#440]
The last two releases are missing pre-built windows binaries. The last pre-built binary is for v0.15.0, which did not work for me on a Windows 2012 R2 server.

**Comment by shmutalov** [comment]
Any news?

**Comment by hoveywankenobi** [comment]
@buger - Any updates on this? Would like to use GOR for some upcoming testing but have not had success getting it to build from source on Windows. Attempted following http://opensourceconnections.com/blog/2016/06/08/building-go-replay-gor-on-windows/

**Comment by alexberry** [comment]
I have just built from the latest branch myself, the cause of the issue is in c:\mingw\include\stdio.h (required  by stdio.h). In stdio.h, comment out line 345 (extern int __mingw_stdio_redirect__(snprintf)...etc) and line 349 (exter int __mingw_stdio_redirect__(vsnprintf)...etc). Both of these lines are broken and neither are referenced by pcap.h, so they are safe to comment out.

Another hint, though it's not necessary, is adjusting go build command to add a version:

go build -ldflags="-X main.VERSION=0.16.1 -extldflags \"-static\""

**Comment by buger** [comment]
Based on all feedback I decided to start shipping windows binaries again, and here is latest master, pls test it out. As mentioned above it build with https://nmap.org/npcap/ and you need to install it if you want capture traffic from localhost.

Note that capturing on loopback on windows is quite different, and in some cases it may require passing custom bpf filter and specify loopback IP, or omiting it, like this: --input-raw-bpf-filter "port 80" (in addition to specifying port in --input-raw argument).

thank you!

[goreplay.zip](https://github.com/buger/goreplay/files/1696582/goreplay.zip)

**Comment by dudleycarr** [comment]
@buger Could you please provide the instructions for building on Windows?

**Comment by sgopalakrishnan1980** [comment]
@buger I am looking to compile this for a Windows 2008 server. Can you please provide me with instructions for the same. Also what is the version of the gor provided in the zip file above. I dont get a version number printed when i run it on Windows Server 2008
