### ISSUE TITLE
Connecting to Kafka brokers via TLS does not work

### ISSUE THREAD

**Issue by michaeljohnsondai** [buger/goreplay#744]
Using the TLS port of a Kafka broker does not work. An error is produced while connecting:

`Failed to start Sarama(Kafka) producer: kafka: client has run out of available brokers to talk to (Is your cluster reachable?)`

Example: (9094 is TLS port)
`usr/local/bin/gor --input-raw :80 --output-kafka-host my.tls-kafka-host:9094 --output-kafka-topic myoutputtopic --output-kafka-json-format --verbose`

**Comment by davidFR** [comment]
GoReplay use sarama for connecting to kafka. Sarama supports TLS but GoReplay don't have this config yet.
I purpose a PR with three arguments (cacert, cert and key) to activate Mutual TLS.

Kafka tests are OK for me but PR build failed on travis because of  TestRAWInputIPv4. I check master and this test fails also...

**Comment by urbanishimwe** [comment]
@davidFR that sounds good to me!
Cc: @buger
