### ISSUE TITLE
When I used Gorepaly to output the recorded content to the file, the ICONS of three little monkeys appeared. May I ask why? Can I change this icon to a string?

### ISSUE THREAD

**Issue by pengsilong** [buger/goreplay#776]
![image](https://user-images.githubusercontent.com/42997980/85287507-f3800880-b4c6-11ea-91a2-0ee8bf488acb.png)

**Comment by buger** [comment]
Hi! 

So essentially GoReplay has a text format, and you can even modify it by hands, or some command-line tools/scripts, and it still work. The monkeys are here, because I needed an unique separator for the messages. 

Do you have any specific issues with these symbols? I just want to understand your use-case. 
Also here is more details on the file format, if you need to parse it https://github.com/buger/goreplay/wiki/Saving-and-Replaying-from-file#file-format

Thank you!

**Comment by pengsilong** [comment]
> 嗨！
> 
> 因此，GoReplay本质上具有文本格式，您甚至可以手动或某些命令行工具/脚本对其进行修改，并且仍然可以使用。猴子在这里，因为我需要消息的唯一分隔符。
> 
> 这些符号是否有任何特定的问题？我只想了解您的用例。
> 另外，如果您需要解析文件格式，则这里是有关文件格式的更多详细信息，[https：//github.com/buger/goreplay/wiki/Saving-and-Replaying-from-file#file-format](https://github.com/buger/goreplay/wiki/Saving-and-Replaying-from-file#file-format)
> 
> 谢谢！



Thank you for your reply, I understand! Thank you very much.

**Comment by pengsilong** [comment]
> Hi!
> 
> So essentially GoReplay has a text format, and you can even modify it by hands, or some command-line tools/scripts, and it still work. The monkeys are here, because I needed an unique separator for the messages.
> 
> Do you have any specific issues with these symbols? I just want to understand your use-case.
> Also here is more details on the file format, if you need to parse it https://github.com/buger/goreplay/wiki/Saving-and-Replaying-from-file#file-format
> 
> Thank you!

Excuse me, how can I use java to analyze these three little monkeys?

**Comment by buger** [comment]
Java provides Scanner class similar to the Go https://www.netjstech.com/2016/06/reading-delimited-file-in-java-using-scanner.html

So just run the scanner mentioned above with `\n🐵🙈🙉\n` delimiter.

**Comment by pengsilong** [comment]
> Java provides Scanner class similar to the Go https://www.netjstech.com/2016/06/reading-delimited-file-in-java-using-scanner.html
> 
> So just run the scanner mentioned above with `\n🐵🙈🙉\n` delimiter.

thank you very much!
